name: codex-preflight
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install (best-effort)
        run: npm ci || npm i --prefer-offline
      - name: Preflight (auto-fix for codex/*)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          git config user.name "codex-bot"
          git config user.email "codex-bot@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git

          # Auto-fix only for codex/* branches (works for push and PR)
          if [[ "${{ github.ref_name }}" == codex/* || "${{ github.head_ref }}" == codex/* ]]; then
            node .github/tools/codex-preflight.mjs --base "${{ github.base_ref || 'main' }}" --fix || true
            if [ -n "$(git status --porcelain)" ]; then
              git commit -am "chore: preflight autofix (format/lockfile)"
              git push origin HEAD:${{ github.ref_name || github.head_ref }}
            fi
          fi

          # Enforce pass
          node .github/tools/codex-preflight.mjs --base "${{ github.base_ref || 'main' }}"
