name: Templates Sentinel
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Block deletion or empties of templates
        shell: bash
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          changed="$(git diff --name-status "$base" "$head")"
          echo "$changed"

          for f in .github/pull_request_template.md .github/ISSUE_TEMPLATE/ux-stage.md; do
            if echo "$changed" | grep -E "^D\s+$f$|^R[0-9]*\s+.*\s+$f$"; then
              echo "::error::$f was deleted or renamed. This is not allowed."
              exit 1
            fi
            if [ ! -f "$f" ]; then
              echo "::error::$f not present in PR head."
              exit 1
            fi
            if [ ! -s "$f" ]; then
              echo "::error::$f is empty."
              exit 1
            fi
          done
          echo "Templates present and non-empty."
